name: Build mujoco_wasm3

on:
  pull_request:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: mymindstorm/setup-emsdk@v11

      - name: Verify Emscripten is Installed
        run: emcc -v

      - name: Compilation
        run: |
          mkdir build
          cd build
          emcmake cmake ..
          make
